config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#index'
  resources :products do
    delete "/products/:id", to: "products#destroy"
    resources :bookings
  end

  resources :users, only: %i[index show] do
    resources :products
    get "/dashboard", to: "dashboards#index"
    delete "/products/:id", to: "dashboards#destroy"
    resources :bookings
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :date, presence: true
  validates :status, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :name, presence: true
  validates :category, presence: true
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  include PgSearch::Model
  pg_search_scope :search_by_name_and_category,
    against: %i[name category],
    using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }

  # has_one_attached :image
  # validates :price, presence: true
  # validates :available, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :bookings_as_owner, through: :products, source: :bookings
  validates :role, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # before_action :set_user

  def index
    # @user = User.find(params[:user_id])
    # @bookings = Booking.where(user_id: @user.id)
    # @products = Product.where(user: current_user)
    # end

    if current_user.role == "owner"
      @bookings = current_user.bookings_as_owner
      @products = Product.where(user: current_user)
    end
    @customer_booking = Booking.where(user: current_user)
  end

  def new
    @booking = Booking.new()
    @product = Product.find(params[:product_id])
    # @booking.product = Product.find(params[:product_id])
    # @previous_booking = Booking.where(user: current_user, product: @product)
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.product = Product.find(params[:product_id])
    @booking.status = "pending"
    if @booking.save!
      redirect_to products_path, alert: 'Congratulations! You have rented gear!'
    else
      render :new
    end
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    user_bookings_path(current_user)
  end

  def show
    @booking = Booking.new
    @product = Product.find(params[:product_id])
  end

  private

  def booking_params
    params.require(:booking).permit(:status, :product_id, :date, :user_id)
  end

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :set_user

  def index
    @users = User.find(params[:user_id])
    @products = Product.where(user_id: @user.id)
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # before_action :set_user
  before_action :set_product, only: %i[edit update show destroy]

  def index
    if params[:query].present?
      @products = Product.search_by_name_and_category(params[:query])
    else
      @products = Product.all
      @markers = @products.geocoded.map do |product|
        {
          lat: product.latitude,
          lng: product.longitude
        }
      end
    end
  end

  def new
    @product = Product.new
    @booking = Booking.new
    @product.user = current_user
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    @booking = Booking.new
  end

  def destroy
    @product.destroy
    redirect_to root_path
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to Product.find(params[:id])
    else
      render 'edit'
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :category, :price, :description, :address)
  end

  def set_product
    @product = Product.find params[:id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<%= render 'shared/navbar' %>
<%= render "shared/banner"%>
<%= render "shared/index-toggle"%>
<div class ="page-container">
  <%= render "shared/bookings-card", belongs_to_current_user: true %>
</div>

app/views/bookings/new.html.erb
<%= render 'shared/navbar' %>
<%= render "shared/banner"%>
<%= render "shared/index-toggle"%>

<h1> Create a new booking!! </h1>
<br>
<h2><%= @product.name %></h2>
<%= simple_form_for [@product, @booking] do |f| %>
  <%= f.input :date %>
  <%= f.button :submit, "Book Skill", class: 'btn-orange' %>
<% end %>

app/views/bookings/show.html.erb
<p>this is bookings/show page</p>

app/views/dashboards/index.html.erb
<%= render 'shared/navbar' %>
<%= render "shared/banner"%>
<%= render "shared/index-toggle"%>

<div class="dashboard-container">
  <div class="personal-info-container">
    <div class= "personal-info-top">
      <h2> My personal information </h2>
      <%= link_to "Edit", "", class: "btn-secondary"  %>
    </div>
    <div class= "personal-info-bottom">
      <h4> <strong>Name: </strong><%=@user.first_name%></h4>
      <h4> <strong>Last Name: </strong><%=@user.last_name%></h4>
      <h4> <strong>Address: </strong><%=@user.address%></h4>
      <h4> <strong>Date of birth: </strong><%=@user.dob%></h4>
      <h4> <strong>Email: </strong><%=@user.email%></h4>
    </div>
  </div>


  <div class="my-gear-container">
    <div class= "gear-card-top">
      <h2> My gear </h2>
      <%= link_to "Add Gear", new_product_path, class: "btn-secondary"  %>
    </div>
    <% @products.each do |product| %>
    <div class="gear-card-bottom">
      <img src="https://source.unsplash.com/random/?<%= product.name %>" />
        <h3><%= product.name %></h3>
          <%= link_to "Edit", edit_product_path(product.id), class:"btn-orange" %>
          <%= link_to "Delete", product_path(product.id), method: :delete,data:   {   confirm: "Are you sure" }, class: "btn-orange" %>
        </div>
    <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sharegear</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>jQuery UI Datepicker - Default functionality</title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
    <script>
    document.addEventListener("turbolinks:load", function() {
   $( "#booking_date" ).datepicker({
      dateFormat: 'dd-mm-yy'
   });
})
  </script>
<link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
<script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
  </head>

  <body>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
  <%= render 'shared/navbar' %>
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<div class="container text-center">
  <%= link_to "Browse products", products_path, class: "btn btn-primary" %>
</div>

app/views/products/edit.html.erb
<h2>Edit Product</h2>
<%= render 'shared/navbar' %>
<%= render "shared/banner"%>
<%= render 'shared/new-product' %>

app/views/products/index.html.erb
<%= render 'shared/navbar' %>
<%= render "shared/banner"%>
<%= render "shared/index-toggle"%>
<%= render "shared/product-card"%>

app/views/products/new.html.erb
<%= render 'shared/navbar' %>
<%= render 'shared/new-product' %>

app/views/products/show.html.erb
<%= render 'shared/navbar' %>
<%= render "shared/banner"%>
<%= render "shared/productshow"%>

app/views/shared/_banner.html.erb
<div class="banner-container">
    <div class="banner-content">
      <h1>We've got your back!</h1>
      <h1>Pack in a little adventure with</h1>
      <h1>the help of your neighbor!</h1>
      <h1>Renting gear has never been so easy.</h1>
  <div class="search-bar">
  <%# searchbar-form %>
    <%= form_tag products_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a product"
      %>
    <% end %>
  <%# searchbar %>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-sm-8">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_booking_card.html.erb
<h1>Welcome to My Bookings/index page!</h1>
<div class= "card-booking-container">
  <div class = "booking-cards">
    <% @bookings.each do |booking| %>
      <div class="booking-card">
        <div class="booking-card-top">
          <h2>Product: <%= booking.product.name %></h2>
          <p>Date: <%= booking.date %></p>
        </div>
        <div class="booking-card-bottom">
          <p>Status: <%= booking.status %></p>
          <%= link_to "Cancel", "#", class: "btn-booking" %>
          <%= link_to "Decline", "#", class: "btn-booking" %>
        </div>
         <img src="https://source.unsplash.com/random/?">
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_bookings-card.erb
<div class= "booking-index-card-top">
  <h2> My booked services/ owner </h2>
</div>
<div class="bookings-index-container">
  <% @bookings.each do |b| %>
  <div class="booking-index-card-bottom">
    <img src="https://source.unsplash.com/random/?<%= b.product.name %>" />
    <h3><%= b.product.name  %></h3>
    <h3>Bookings date:<%= b.date%></h3><br>
    <%= simple_form_for [current_user, b] do |f| %>
      <%= f.input :status, label: 'Status:', collection:['pending','confirm', 'cancel'] %>
      <%= f.button :submit, "Submit", class: 'btn-orange' %>
    <% end %>
  </div>
  <% end %>
</div>

<div class= "booking-index-card-top">
  <h2> My bookings !! (customer) </h2>
</div>
<div class="bookings-index-container">
  <% @customer_booking.each do |b| %>
  <div class="booking-index-card-bottom">
    <img src="https://source.unsplash.com/random/?<%= b.product.name %>" />
    <h3> <%= b.product.name %></h3>
    <p>Booked for: <%= b.date%></p><br>
    <p>Status: <%= b.status %></p>
    <p><%= b.product.description%></p>
    <p>Owner: <%= b.product.user.first_name%>
  </div>
  <% end %>
</div>

app/views/shared/_button.html.erb
<a class="btn-secondary" href="#"></a>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_index-toggle.html.erb
<%# bootstrap toggle %>
<div class="index-toggle-container">
  <p>
    <a class="btn btn-primary" data-bs-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">Camp & Hike</a>
    <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#multiCollapseExample2" aria-expanded="false" aria-controls="multiCollapseExample2">Watersports</button>
      <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#multiCollapseExample3" aria-expanded="false" aria-controls="multiCollapseExample3">Snow</button>
      <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#multiCollapseExample4" aria-expanded="false" aria-controls="multiCollapseExample4">Climbing</button>
      <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#multiCollapseExample5" aria-expanded="false" aria-controls="multiCollapseExample5">Cycling</button>
    <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target=".multi-collapse" aria-expanded="false" aria-controls="multiCollapseExample1 multiCollapseExample2">Exit All</button>
  </p>
  <div class="row">
    <div class="col">
      <div class="collapse multi-collapse" id="multiCollapseExample1">
        <div class="card card-body">
          Some placeholder content for the first collapse component of this multi-collapse example. This panel is hidden by default but revealed when the user activates the relevant trigger.
        </div>
      </div>
    </div>
    <div class="col">
      <div class="collapse multi-collapse" id="multiCollapseExample2">
        <div class="card card-body">
          Some placeholder content for the second collapse component of this multi-collapse example. This panel is hidden by default but revealed when the user activates the relevant trigger.
        </div>
      </div>
    </div>
    <div class="col">
      <div class="collapse multi-collapse" id="multiCollapseExample3">
        <div class="card card-body">
          Some placeholder content for the second collapse component of this multi-collapse example. This panel is hidden by default but revealed when the user activates the relevant trigger.
        </div>
      </div>
    </div>
    <div class="col">
      <div class="collapse multi-collapse" id="multiCollapseExample4">
        <div class="card card-body">
          Some placeholder content for the second collapse component of this multi-collapse example. This panel is hidden by default but revealed when the user activates the relevant trigger.
        </div>
      </div>
    </div>
    <div class="col">
      <div class="collapse multi-collapse" id="multiCollapseExample5">
        <div class="card card-body">
          Some placeholder content for the second collapse component of this multi-collapse example. This panel is hidden by default but revealed when the user activates the relevant trigger.
        </div>
      </div>
    </div>
  </div>
</div>
<%# end bootstrap toggle %>

app/views/shared/_landing-banner.html.erb
<div class="landing-background-container">
<ul class="navbar-logo">
      <li><a href="/products"><%= image_tag "white-share-gear.png" %></a></li>
    </ul>
    <div class="overlay">
    Start your adventure. <br/>save on gear <a href="/products" class="btn-orange" style="text-decoration: none; padding-top: 4px;">start renting</a>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <ul class="navbar-logo">
      <li><a href="/products"><%= image_tag "ShareGearLogo.png" %></a></li>
    </ul>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <div class="navbar-text">
            <li class="nav-item active">
              <%= link_to "Home", products_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Location", "#", class: "nav-link" %>
            </li>
          </div>
          <li class="nav-item dropdown">
            <%= image_tag "https://www.shareicon.net/data/512x512/2015/12/25/692753_vertical_512x512.png", class: "dots-dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My account", user_dashboard_path(current_user), class: "dropdown-item" %>
              <%= link_to "My bookings", user_bookings_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_new-product.html.erb
<div class="form-margins">
<h2> New Gear </h2>
  <%= simple_form_for [ @product ] do |f| %>
    <div class="product-description-container">
      <%= f.input :name %>
      <%= f.input :category, collection: ["camp & hike", "watersports", "cycling", "climbing", "snow"] %>
      <%= f.input :price %>
      <%= f.input :address %>
      <%= f.input :description %>
    </div>
    <%= f.submit "Submit your gear", class: "btn-orange" %>
  <% end %>
<div>

app/views/shared/_product-card.html.erb
  <div class="card-product-container">
    <div class="cards">
      <% @products.each do |product| %>
        <div class="card-product">
          <%= link_to product_path(product.id) do %>
          <img src="https://source.unsplash.com/random/?<%= product.name %>" />
            <div class="card-product-footer">
              <div style="text-decoration:none;">
                <h2><%= product.name %></h2>
                <p>Owner <%= product.user.first_name %></p>
              </div>
              <h2><%= product.price %></h2>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

    <div style="width: 45%; height: 100vh, position: sticky;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>

app/views/shared/_productshow.html.erb
  <div class="card-productshow">
    <div class="card-productshow-left">
      <img src="https://source.unsplash.com/random/?<%= @product.name %>" />
        <div class="card-productshow-left-bottom">
          <h2><%= @product.name %></h2>
            <div class="productshow-info">
              <p>$<%= @product.price %> per day </p>
              <div class="productshow-buttons"style="float:right;">
                <%= link_to "Book Now", new_product_booking_path(@product.id), class:'btn-orange' %>
                <%= link_to "All products", products_path, class: 'btn-orange' %>
              </div>
            </div>
        </div>
    </div>
    <div class="card-productshow-right">
      <p>Description</p>
      <br>
      <p><%= @product.description %></p>
    </div>
  </div>






<%# <p><%= cl_image_path @product.photo.key %>

app/views/users/index.html.erb
<%= render "shared/landing-banner"%>

app/views/users/show.html.erb
<%= render 'shared/navbar' %>
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>